### ISSUE TITLE
Ignore bank account for which operations can't be retrieved

### ISSUE THREAD

**Issue by Thatoo** [bnjbvr/kresus#106]
Hello,

Kresus worked one time, just after installation, but since then, when I try to sync the data, I obtain this error : 
xhr error: Not Found
bank access not found

What does it mean? How can I solve it?

Thanks,
![capture du 2015-05-17 11 34 53](https://cloud.githubusercontent.com/assets/464782/7669769/0ee381ca-fc8e-11e4-830f-7eb7ae47c6c8.png)

**Comment by bnjbvr** [comment]
Hi! I think that when you setup an account for the first time but things don't get well (for instance, operations or accounts import get aborted for some reason), data is in an unstable state and then you can't fetch new transactions.
Can you try deleting your bank in the Settings section, and restart the process entirely, please?

**Comment by Thatoo** [comment]
I tried to do so but when I start to import the account, I have this error : 
"
xhr error: Internal Server Error
when retrieving operations: Error when parsing weboob json: 'content' 
"
![kresus error](https://cloud.githubusercontent.com/assets/464782/7831264/c424605a-045d-11e5-86e1-85ab3756115b.jpeg)

**Comment by bnjbvr** [comment]
Ha, I have never seen this before. Any chance you could remove Kresus and all its data (through the DataBrowser app) and try again? If you know how to use weboob/boobank, I'd be curious to know whether your issue reproduces with these too, or if it is specific to kresus.

**Comment by Thatoo** [comment]
Ok, I can try to remove Kresus and all it's data. What data should I delete in DataBrowser? (I don't want to delete data that are shared with other app. I don't know weboob/boobank, sorry.

**Comment by bnjbvr** [comment]
Thanks! Removing all BankAccess / BankAccount / BankOperation / KresusConfig should be enough.

**Comment by Thatoo** [comment]
I did it! Here is the error that occur at the first "import".
********* is normally a list of banking operation, similar to the first and last one.
I don't know weboob/boobank. Sorry about that
How can I help?

xhr error: Internal Server Error
when retrieving operations: Error when parsing weboob json: The account type has not been implemented by weboob.
The account type has not been implemented by weboob.
{"bred": [{"account": "0074364.000", "label": "GOOGLE *LiveQos", "raw": "GOOGLE *LiveQos Carte 00099   LE 01/06/15 CB.600633 ORIGINE GBR 10 EUR", "amount": "-1.6", "rdate": "2015-05-31T00:00:00Z", "date": "2015-05-31T00:00:00Z"}, ********* {"account": "0074364.000", "label": "Virement automatique 31012", "raw": "Virement automatique 3012 MR LETRE             ECH0115 REF

![capture d ecran 2015-06-04 a 22 54 13](https://cloud.githubusercontent.com/assets/464782/8003500/bd7d6ad8-0b80-11e5-80cf-c1bc7f34c102.jpg)

**Comment by bnjbvr** [comment]
Thanks for the input. It seems that weboob can read an account but can't import the operations. In this case, I guess Kresus should just shut up and skip the account. I'll fix this soon.

**Comment by Thatoo** [comment]
ok.
Let me know when I should try again. I'll delete the data again.
Thank you for your investment for cozy-cloud and the futur users.
Thatoo

**Comment by bnjbvr** [comment]
@Thatoo : I've submitted a patch in `incoming`. Can you uninstall Kresus, and install the incoming version? (that would be by entering `https://github.com/bnjbvr/kresus.git@incoming` in the installation text field on the config page)

**Comment by Thatoo** [comment]
@bnjbvr : done! The first import worked well. I'll let you know how it works for the next sync and see how it evolves.
Thank you,

**Comment by Thatoo** [comment]
It seems that it's working except a weird thing.
Synchronisation are working.
By aacount, "Reçu", "Payé and "Economisé" seems correct.
However, "Balance" is really weird. I can't see what it is link to... is it suppose to be "le solde du compte"? If it is, they are all wrong.

**Comment by ZeHiro** [comment]
It is supposed to be solde du compte. But it is computed live. At the first import, an initial value is put inside the db (calculated based on  imported value of 'solde'+ operations) and the current sold is calculated taking into account all operations. If you have a wrong initial value or missing operations  (accounts are never deleted even when kresus is uninstalled) then the solde can ba wrong.

**Comment by Thatoo** [comment]
ok, thank you for this information, but what should I do?
I've just installed Kresus...

**Comment by ZeHiro** [comment]
wait for @bnjbvr :)

**Comment by bnjbvr** [comment]
@Thatoo, there are several possible causes for this issue:

1. there were already operations / accounts before you registered your first account, in which case deleting all Kresus data (again...) would solve it. If you've done this before installing the incoming version of Kresus, it probably is less likely to be the cause of your issue. In case all other solutions don't work, you can retry that!
2. there could be duplicate operations. You can check them in "duplicate operations" and merge them together. However, after a first import, there shouldn't be any.

So yeah, if 2 doesn't work, I would suggest retrying 1. However, if the difference stays around, I am afraid I won't be able to debug it remotely. I'll try to see whether I can reproduce locally on my account though. If you can find where the differences come from (that is, which operations), maybe I can help, but I understand that's a tedious task... Good luck!

**Comment by Thatoo** [comment]
I've done 2, but it doesn't solve the problem. There were few "duplicate" but at the same time, I was not sure they were real "duplicate" because they had different "titles" even though they had the same ammount at the same date...
So 'Ill delete again BankAccess / BankAccount / BankOperation / KresusConfig, uninstall and reinstall Kresus from https://github.com/bnjbvr/kresus.git@incoming and I'll try again.
I'll let you know the result.

**Comment by Thatoo** [comment]
I can't delete BankAccess neither BankOperation...
![kresus-no bank operation](https://cloud.githubusercontent.com/assets/464782/8227719/2d68d842-15b2-11e5-9e1f-7a99af91dd18.png)

**Comment by bnjbvr** [comment]
Weird, seems like an issue in the data browser (feel free to open an issue there, maybe?). An other option is to delete the entire tables ("bankoperations" and "bankaccess"), this should work as well.

**Comment by Thatoo** [comment]
done, I've deleted all the four tables and reinstall Kresus.
I'll make the first import later and will let you know if it finaly worked.

**Comment by Thatoo** [comment]
It's going to be more complicated because I can't install Kresus : 

Kresus
Application cassée
Cette application est cassée. Vous pouvez essayer de la réinstaller: réinstallation.
Si l'erreur persiste, vous pouvez nous contacter par mail à contact@@cozycloud.cc ou sur IRC #cozycloud sur irc.freenode.net.
Application already exists : Error: Application already exists at /usr/lib/node_modules/cozy-controller/build/server/controllers/applications.js:74:13 at startApp (/usr/lib/node_modules/cozy-controller/build/server/lib/controller.js:45:12) at Object.module.exports.install (/usr/lib/node_modules/cozy-controller/build/server/lib/controller.js:198:12) at Object.module.exports.install [as handle] (/usr/lib/node_modules/cozy-controller/build/server/controllers/applications.js:71:21) at next_layer (/usr/lib/node_modules/cozy-controller/node_modules/americano/node_modules/express/lib/router/route.js:103:13) at Object.module.exports.check [as handle] (/usr/lib/node_modules/cozy-controller/build/server/middlewares/token.js:31:16) at next_layer (/usr/lib/node_modules/cozy-controller/node_modules/americano/node_modules/express/lib/router/route.js:103:13) at Route.dispatch (/usr/lib/node_modules/cozy-controller/node_modules/americano/node_modules/express/lib/router/route.js:107:5) at /usr/lib/node_modules/cozy-controller/node_modules/americano/node_modules/express/lib/router/index.js:213:24 at param (/usr/lib/node_modules/cozy-controller/node_modules/americano/node_modules/express/lib/router/index.js:303:14)

And if I go back to allmydata, Kresus appear three time in the list.
I'm trying to delete Kresus from "Etats", it says "en cours de suppression" but it never ends...

**Comment by Thatoo** [comment]
It's ok, after some update, some delete, uninstall and stuff, I'm back to normal, all Kresus database erased and the three Kresus uninstall.
So, should I try installing https://github.com/bnjbvr/kresus.git@incoming again?

**Comment by eravion** [comment]
From my side, I'm using incoming and it looks to fix BNP account issue.

**Comment by eravion** [comment]
I think an old bug is back, the Balance/Receive amount are not ok

**Comment by ZeHiro** [comment]
HAve you checked "doublons"?

**Comment by Thatoo** [comment]
I'll wait for your answer @eravion before reinstalling incoming Kresus.

**Comment by eravion** [comment]
No doublon. 
The difference between amount in BNP website and amount in Kresus is huge.

**Comment by ZeHiro** [comment]
could this be due to a wrong initial amount?
Did you also remove the bankaccess before reimoprting? 
Kresus works like that :

**Comment by bnjbvr** [comment]
@eravion If the failure has been "long enough" (for Credit Mutuel, that would be 3 months though), I am afraid you may have lost any statement lines in the meanwhile, which may be the cause of the difference. Any chance that you can correlate the difference with any operations? Maybe you can see how many operations in total you have for this month in Kresus, and compare with the number of operations you have in your bank? (and if it's not this month, might it be last month, etc.)

Have you deleted any bank information before installing the incoming version? (shouldn't be necessary) If so, you would need to delete all the data indicated in one of the above comments.

**Comment by eravion** [comment]
I removed everything and add my account again, now it is clean.
Of course all data were lost, that's the risk when you are beta tester :)
This version look stable and I confirm that the graph are nice.
Thanks for your good job.

**Comment by Thatoo** [comment]
ok, so I deleted everything and I'm going to try again as it seems to work for @eravion

**Comment by Thatoo** [comment]
Kresus installed. with the incoming but I have again an error at the first import : 
xhr error: Internal Server Error
Weboob error: /usr/local/cozy/apps/kresus/weboob/env/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "py/endpoint.py", line 109, in <module>
    content = BankHandler(id, password, website).post(bankuuid)
  File "py/endpoint.py", line 66, in post
    return self.load_from_connector(name)
  File "py/endpoint.py", line 46, in load_from_connector
    raise Exception("Unexpected Weboob error: %s" % unicode(e))
Exception: Unexpected Weboob error: 'LoginPage' object has no attribute 'iter_accounts'

**Comment by Thatoo** [comment]
I installed again Incoming Kresus and I did again the first import. It seems to work this time. "La Balance" is iqual to "Solde" on the bank website.
